# 1. 텐서

텐서(Tensor)는 파이토치의 기본 단위이며 GPU 연산을 가능하게 한다. 또한 Numpy의 배열과 유사하여 손쉽게 다룰 수 있다.

## 1.1 텐서 만들기

In [1]:
# 라이브러리 불러오기
import torch # Pytorch를 사용하기 위한 기본 라이브러리다.
import numpy as np # Numpy를 사용하기 위한 기본 라이브러리다. 여기서 "as np"는 numpy를 np로 짧게 표기하겠다는 뜻이다.

In [2]:
# 빈 텐서 생성
x = torch.empty(5,4) # 5x4 행렬 생성
print(x) # 초기화되지 않은 행렬인 경우 해당 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타난다.

tensor([[-6.7128e-05,  3.0960e-41,  7.0065e-44,  7.0065e-44],
        [ 6.3058e-44,  6.7262e-44,  7.1466e-44,  6.3058e-44],
        [ 7.0065e-44,  7.1466e-44,  1.1771e-43,  6.7262e-44],
        [ 7.7071e-44,  8.1275e-44,  7.1466e-44,  7.1466e-44],
        [ 8.1275e-44,  6.7262e-44,  7.5670e-44,  6.4460e-44]])


In [3]:
torch.ones(3,3) # 3x3 일 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2) # 2행 영 벡터

tensor([0., 0.])

In [5]:
torch.rand(5,6) # 5x6 랜덤 행렬

tensor([[0.1416, 0.0396, 0.8485, 0.8886, 0.1406, 0.4391],
        [0.1839, 0.0062, 0.2245, 0.7415, 0.1057, 0.9652],
        [0.0154, 0.3656, 0.9637, 0.6096, 0.6257, 0.7280],
        [0.6896, 0.0286, 0.4382, 0.7000, 0.2699, 0.8731],
        [0.2617, 0.3657, 0.1945, 0.8417, 0.5448, 0.4381]])

## 1.2 리스트, 넘파이 배열을 텐서로 만들기

In [10]:
l = [13,4] # 리스트 생성
r = np.array([4,56,7]) # 넘파이 배열 생성
print(r)

[ 4 56  7]


In [11]:
torch.tensor(l) # 리스트를 텐서로 쉽게 변환할 수 있다.

tensor([13,  4])

In [12]:
torch.tensor(r) #넘파이 배열을 텐서로 쉽게 변환할 수 있다.

tensor([ 4, 56,  7])

## 1.3 텐서의 크기와 타입 확인하기

In [13]:
x.size()[1] # .size()는 텐서의 크기를 확인할 수 있으며 매우 자주 사용된다.

4

In [14]:
type(x) # type은 Python에서 사용되는 모든 것들을 종류를 보여준다. 

torch.Tensor

## 1.4 텐서의 덧셈

In [15]:
x = torch.rand(2,2) # 2x2 랜덤 행렬
y = torch.rand(2,2) # 2x2 랜덤 행렬
print(x)
print(y)

tensor([[0.4868, 0.7148],
        [0.6571, 0.1043]])
tensor([[0.9570, 0.2508],
        [0.8592, 0.2450]])


In [16]:
x+y # 두 텐서의 합

tensor([[1.4438, 0.9657],
        [1.5163, 0.3494]])

In [17]:
torch.add(x,y) # 두 텐서의 합의 또 다른 표현

tensor([[1.4438, 0.9657],
        [1.5163, 0.3494]])

In [18]:
y.add(x) # 두 텐서의 합의 또 다른 표현이지만 이는 y에 x를 더한다는 의미다.

tensor([[1.4438, 0.9657],
        [1.5163, 0.3494]])

In [19]:
print("원래 y: ", y)
y.add_(x)
print("y=y+x: ",y)

# y.add_는 y에 x를 더한 값을 y에 대체한다.(inplace 방식)

원래 y:  tensor([[0.9570, 0.2508],
        [0.8592, 0.2450]])
y=y+x:  tensor([[1.4438, 0.9657],
        [1.5163, 0.3494]])


## 1.5 텐서의 크기 변환하기

In [20]:
x = torch.rand(8,8) # 8x8 랜덤 행렬
print(x.size())

torch.Size([8, 8])


In [21]:
a = x.view(64) # 크기를 바꿔주는 view 8x8 -> 64
print(a.size())

torch.Size([64])


In [22]:
b = x.view(-1,4,4) # -1은 원래 크기가 되게 하는 값 8x8 -> -1x4x4 즉, 4x4x4이다.
print(b.size()) 

# 따라서 -1은 원래 크기가 되게 하는 값이 자동으로 지정되기 때문에 한 번만 사용할 수 있다. 
# 예를 들어 x.view(-1,-1,4)와 같은 선언은 오류가 난다.

torch.Size([4, 4, 4])


## 1.6 텐서에서 넘파이로 만들기

In [23]:
x = torch.rand(8,8)
y = x.numpy() # .numpy()로 매우 간단하게 넘파이 배열로 만들 수 있다.
print(y)

[[0.73688984 0.40384215 0.842727   0.45701844 0.31829417 0.02200365
  0.07466614 0.8031926 ]
 [0.6238382  0.89950293 0.7203828  0.8826086  0.02164531 0.26364076
  0.42304862 0.4958411 ]
 [0.11489844 0.2821064  0.11317289 0.39064884 0.47547835 0.7923261
  0.94721216 0.65194   ]
 [0.28351623 0.4517128  0.81412303 0.94836104 0.1024797  0.9207281
  0.24589485 0.5896515 ]
 [0.07399303 0.35611475 0.606369   0.59341764 0.16750681 0.17863011
  0.98210263 0.96710926]
 [0.6182484  0.01249248 0.35705763 0.5273843  0.4059325  0.15478045
  0.38704467 0.847062  ]
 [0.53178746 0.7251014  0.45544904 0.0703283  0.6227283  0.6313556
  0.60866815 0.6028373 ]
 [0.989837   0.89765835 0.83892804 0.20440048 0.34557384 0.00580478
  0.3374489  0.84248763]]


In [24]:
type(y)

numpy.ndarray

## 1.7 단일 텐서에서 값으로 뽑아내기

In [25]:
x = torch.ones(1)

In [26]:
print(x)
print(x.item()) # .item()은 손실 함숫값과 같이 숫자가 하나인 텐서를 텐서가 아닌 값으로 만들어 준다.

tensor([1.])
1.0
